# Generated by Django 5.1.1 on 2024-09-29 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.CharField(default=5, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="professional",
            field=models.CharField(default="sample", max_length=25),
            preserve_default=False,
        ),
    ]
